name: Terraform Azure Deployment
on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        working-directory: ./terraform   # Change directory to the specific Terraform directory
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform   # Change directory to the specific Terraform directory
        run: terraform plan

      - name: Terraform Apply
        working-directory: ./terraform   # Change directory to the specific Terraform directory
        run: terraform apply -auto-approve

      - name: Terraform Show Output
        working-directory: ./terraform   # Change directory to the specific Terraform directory
        run: terraform output -json > terraform_output.json

